version: "3"

services:
  inotify_discord:
    image: quay.io/michael_silich/tools:latest
    container_name: inotify-discord
    environment:
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/your-webhook-url
    volumes:
      - /path/to/your/folder:/folderwatch:ro
